# -*- coding: utf-8 -*-
"""Student Attendance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqUyEb6BP1W5uTj0VXce8utaAVxVdPbf
"""

attendance_records = [
    {"name": "Kamal Perera",     "id": "SIF001", "attended": 18, "total": 20},
    {"name": "Nimal Silva",      "id": "SIF002", "attended": 12, "total": 20},
    {"name": "Sanduni Fernando", "id": "SIF003", "attended": 20, "total": 20},
]

def add_student_attendance():
    print("\n--- Add Student Attendance ---")
    name = input("Enter Student Name: ").strip()
    student_id = input("Enter Student ID: ").strip()

    for record in attendance_records:
        if record["id"] == student_id:
            print(f"Error: Student ID '{student_id}' already exists.")
            return

    try:
        classes_attended = int(input("Enter Classes Attended: "))
        total_classes = int(input("Enter Total Classes: "))
    except ValueError:
        print("Error: Please enter valid numbers for classes.")
        return

    if classes_attended > total_classes:
        print("Error: Classes attended cannot be more than total classes.")
        return

    record = {
        "name": name,
        "id": student_id,
        "attended": classes_attended,
        "total": total_classes
    }
    attendance_records.append(record)
    print(f"Student '{name}' added successfully.")


def view_attendance_records():
    print("\n--- All Attendance Records ---")

    if len(attendance_records) == 0:
        print("No records found.")
        return

    print(f"{'No.':<5} {'Name':<20} {'ID':<12} {'Attended':<10} {'Total':<10} {'Percentage':<10}")
    print("-" * 67)

    for i, record in enumerate(attendance_records):
        percentage = calculate_percentage(record["attended"], record["total"])
        print(f"{i + 1:<5} {record['name']:<20} {record['id']:<12} {record['attended']:<10} {record['total']:<10} {percentage:.2f}%")


def search_student():
    print("\n--- Search Student ---")
    search_id = input("Enter Student ID to search: ").strip()

    for record in attendance_records:
        if record["id"] == search_id:
            print(f"\nStudent Found:")
            print(f"  Name            : {record['name']}")
            print(f"  Student ID      : {record['id']}")
            print(f"  Classes Attended: {record['attended']}")
            print(f"  Total Classes   : {record['total']}")
            return

    print(f"No student found with ID '{search_id}'.")


def calculate_percentage(attended, total):
    if total == 0:
        return 0.0
    return (attended / total) * 100


def show_highest_attendance():
    print("\n--- Highest Attendance ---")

    if len(attendance_records) == 0:
        print("No records found.")
        return

    highest = attendance_records[0]
    for record in attendance_records:
        if calculate_percentage(record["attended"], record["total"]) > calculate_percentage(highest["attended"], highest["total"]):
            highest = record

    percentage = calculate_percentage(highest["attended"], highest["total"])
    print(f"Highest Attendance: {highest['name']} (ID: {highest['id']}) - {percentage:.2f}%")


def show_lowest_attendance():
    print("\n--- Lowest Attendance ---")

    if len(attendance_records) == 0:
        print("No records found.")
        return

    lowest = attendance_records[0]
    for record in attendance_records:
        if calculate_percentage(record["attended"], record["total"]) < calculate_percentage(lowest["attended"], lowest["total"]):
            lowest = record

    percentage = calculate_percentage(lowest["attended"], lowest["total"])
    print(f"Lowest Attendance: {lowest['name']} (ID: {lowest['id']}) - {percentage:.2f}%")


def delete_student():
    print("\n--- Delete Student Record ---")
    search_id = input("Enter Student ID to delete: ").strip()

    for i, record in enumerate(attendance_records):
        if record["id"] == search_id:
            confirm = input(f"Are you sure you want to delete '{record['name']}'? (yes/no): ").strip().lower()
            if confirm == "yes":
                attendance_records.pop(i)
                print(f"Student '{record['name']}' deleted successfully.")
            else:
                print("Delete cancelled.")
            return

    print(f"No student found with ID '{search_id}'.")


def main():
    print("=" * 40)
    print("  Student Attendance Management System")
    print("=" * 40)

    while True:
        print("\n--- Main Menu ---")
        print("1. Add Student Attendance")
        print("2. View Attendance Records")
        print("3. Search Student")
        print("4. Calculate Attendance Percentage")
        print("5. Show Highest Attendance")
        print("6. Show Lowest Attendance")
        print("7. Delete Student Record")
        print("8. Exit")

        choice = input("\nEnter your choice (1-8): ").strip()

        if choice == "1":
            add_student_attendance()
        elif choice == "2":
            view_attendance_records()
        elif choice == "3":
            search_student()
        elif choice == "4":
            print("\n--- Calculate Attendance Percentage ---")
            search_id = input("Enter Student ID: ").strip()
            found = False
            for record in attendance_records:
                if record["id"] == search_id:
                    percentage = calculate_percentage(record["attended"], record["total"])
                    print(f"Attendance Percentage for {record['name']}: {percentage:.2f}%")
                    found = True
                    break
            if not found:
                print(f"No student found with ID '{search_id}'.")
        elif choice == "5":
            show_highest_attendance()
        elif choice == "6":
            show_lowest_attendance()
        elif choice == "7":
            delete_student()
        elif choice == "8":
            print("\nExiting the system. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 8.")

main()